### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by djendacott** [katernet/darkmode#1]
The instructions are great, but is there a simple way to uninstall this plugin without breaking anything?

**Comment by katernet** [comment]
I'll add an uninstall option in the next commit.

To uninstall:
```
$ launchctl unload ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
$ launchctl unload ~/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist
```
Delete the following files
~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist ~/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist ~/Library/Logs/io.github.katernet.darkmode.log 
~/Library/Application Support/darkmode (for v1.3: ~/Documents/darkmode)
