### ISSUE TITLE
How do I remove this?

### ISSUE THREAD

**Issue by anaclumos** [katernet/darkmode#13]
Can you please provide some details about how to remove this?
I have enjoyed this a lot, but I now want to get back to one theme.

**Comment by anaclumos** [comment]
Found it!

To uninstall:
```
$ launchctl unload ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
$ launchctl unload ~/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist
```
Delete the following files
~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist ~/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist ~/Library/Logs/io.github.katernet.darkmode.log
~/Library/Application Support/darkmode (for v1.3: ~/Documents/darkmode)

**Comment by notsidney** [comment]
You can also run the original script with the `/u` flag:
```
$ ./darkmode.sh /u
```

It’s right at the bottom of the README file but kinda hard to see
