### ISSUE TITLE
cannot unsinstall

### ISSUE THREAD

**Issue by almabel01** [katernet/darkmode#14]
tried to uninstall many versions from terminal ./darkmode.sh /u (including the last update), once deleted the folder manually, yet mac sets itself to darkmode around sundown 
MBA - macOS Mojave 10.14.1

**Comment by katernet** [comment]
To uninstall manually use [these instructions](https://github.com/katernet/darkmode/issues/1)

Let me know how it goes.

**Comment by almabel01** [comment]
Thank you for your help.
Following the instructions, I uninstalled it, this way it does not change the Alfred theme but **change to dark mode at sundown**. 
Sorry for not being concrete, every time I uninstalled it ( ./darkmode.sh /u) the same thing happened Alfred theme unchanged, dark mode on.
😔
