### ISSUE TITLE
Daylight Savings Time Adjustments

### ISSUE THREAD

**Issue by joshuaseltzer** [katernet/darkmode#17]
Where I live (Eastern Standard Time, United States) I noticed that the darkmode script did not change when Daylight Savings Time kicked in a few weeks ago.  My Nightshift won't kick in until much later in the evening (as expected), but the darkmode script still thinks it's dark outside much earlier in the day.  Before DST went into affect, everything synced up nicely.

I wonder if this is related to #10 ?

**Comment by joshuaseltzer** [comment]
FYI uninstalling and reinstalling the script appeared to solve this for me.  Would be nice if it were able to fix itself for areas which adhere to DST.

**Comment by bandgeekdante** [comment]
I had this bug but I made a couple of edits so that it would update the times every day; this way the DST issue only happens on one day (kind of a band-aid fix)

**Comment by joshuaseltzer** [comment]
@bandgeekdante ideally we'd set it to run at particular days of the year if you live in an area which observed DST. I'm sure there's an API to help us determine that.

**Comment by katernet** [comment]
Hi @joshuaseltzer and @bandgeekdante sorry for the late reply, I've been away. To be honest, my desktop Mac updated the solar times to daylight saving times ok.

I've updated the beta branch with a Daylight Saving Time (DST) checker. 

https://github.com/katernet/darkmode/commit/caac14fde51dd9117abf285553f42831cdbfd3bf

I've added it to the beta branch as I am not confident there are no issues. Please note that this beta also contains code for static sunrise/sunset times, but it shouldn't get in the way of normal usage.

Can you please test and let me know here if there are any issues. Just replace the script ~/Library/Application Support/darkmode.sh with the beta script.

**Comment by joshuaseltzer** [comment]
Sorry I'm also getting back to you so late.  I just uninstalled the old script and installed the beta script on both of my machines.  I'll let you know how it goes.

**Comment by katernet** [comment]
@joshuaseltzer have you had any problems with the beta script, such as things not working, errors etc? Obviously we won't wait until the next daylight saving scheduler (and I think manually changing the date won't kick it in).

**Comment by joshuaseltzer** [comment]
Nope - no issues thus far with the beta on either of my machines. Like you said, however, I cannot confirm it's working until the next daylight savings time kicks in.

**Comment by katernet** [comment]
Cool thanks. I'll look into migrating this into the release soon.
As the next daylight saving start/finish time is around 5 months away, I will close this off. Anyone with issues with the solar time being 1hr late/early for the next daylight saving schedule, please feel free to open an issue.
