### ISSUE TITLE
Sunrise/Sunset does not work

### ISSUE THREAD

**Issue by pelillian** [katernet/darkmode#19]
For some reason when I run the darkmode.sh script it correctly checks the current time and sets the mode accordingly, but does not automatically do so at sunrise and sunset.

```
> launchctl list | grep dark
-	78	io.github.katernet.darkmode.sunrise
-	78	io.github.katernet.darkmode.sunset
```

Mojave 10.14.4
Mid 2015 MacBook

**Comment by katernet** [comment]
Exit code 78 seems to be configuration error. Which version are you running, 1.8.2?

And are you connected to wifi? (Doesn't require to be only connection, primary connection can be ethernet) and is Setting Timezone enabled as per Readme?
Is darkmode allowed in Automation in System Preferences > Security & Privacy > Privacy > Automation ?
What does the log contain?
```
$ cat ~/Library/Logs/io.github.katernet.darkmode.log
```

Also you could try relaunching the launch agent, to see if it then returns a 0 exit code.
```
$ launchctl unload ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
$ launchctl unload ~/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist
$ launchctl load ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
$ launchctl load ~/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist
```

**Comment by pelillian** [comment]
Yeah, I'm running 1.8.2 connected to wifi. I accepted the dialog that popped up about system events but I don't see Darkmode in the list under Automation (iTerm is there if that helps).


Log before relaunching launch agent:
```
08/05/19 09:53:35 darkmode: Solar query stored - Sunrise: 05:59 Sunset: 19:37
05/08/19 21:06:45 /Users/pelillian/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist: Could not find specified service
05/08/19 21:06:45 /Users/pelillian/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist: Path had bad ownership/permissions
13/05/19 18:03:04 darkmode: Solar query stored - Sunrise: 05:52 Sunset: 19:34
13/05/19 18:06:09 darkmode: Solar query stored - Sunrise: 05:52 Sunset: 19:34
13/05/19 18:58:11 darkmode: Solar query stored - Sunrise: 05:52 Sunset: 19:34
```

After relaunching launch agent:
```
> launchctl list | grep dark
-	78	io.github.katernet.darkmode.sunrise
-	0	io.github.katernet.darkmode.sunset
```

Thanks!

**Comment by katernet** [comment]
> 05/08/19 21:06:45 /Users/pelillian/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist: Path had bad ownership/permissions

What are the permissions for sunrise.plist? Run the below

`ls -l ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist`

If they are not `-rw-r--r--  [yourusername]  staff` then run the below and then `launchctl unload` and `launchctl load`

```bash
chmod 644 ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
chown 501:staff ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
```

**Comment by pelillian** [comment]
Here's the result of ls -l:
`-rw-r--r--  1 pelillian  staff  531 May 13 23:00 /Users/pelillian/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist`

**Comment by katernet** [comment]
Before I forget the obvious... what are the permissions on darkmode.sh?

`ls -l ~/Library/Application\ Support\darkmode\darkmode.sh`

Should be `-rwxr-xr-x [yourusername]  staff` (ignore the @ if it shows).

**Comment by katernet** [comment]
Before I forget the obvious... what are the permissions on darkmode.sh?

`ls -l ~/Library/Application\ Support/darkmode/darkmode.sh`

Should be `-rwxr-xr-x [yourusername]  staff` (ignore the @ if it shows).

**Comment by pelillian** [comment]
`-rw-r--r--@ 1 pelillian  staff  7886 May  8 09:46 /Users/pelillian/Library/Application Support/darkmode/darkmode.sh`

And that might be our problem!

After a quick chmod +x:
`-rwxr-xr-x@ 1 pelillian  staff  7886 May  8 09:46 /Users/pelillian/Library/Application Support/darkmode/darkmode.sh`

Anything else I should do or do you think it will work now?

**Comment by katernet** [comment]
@pelillian should be good now. Let me know if dark mode doesn't schedule.

**Comment by pelillian** [comment]
Thanks so much! It seems to be working.
