### ISSUE TITLE
Messages app doesn't fully change mode

### ISSUE THREAD

**Issue by pelillian** [katernet/darkmode#22]
Not sure what's going on here—this might be a macOS limitation—but sometimes (maybe 20% of the time, may be related to whether or not it's open) when I open my laptop in the morning my messages look like this.

## Selected
<img width="790" alt="Messages darkmode bug 1" src="https://user-images.githubusercontent.com/16657986/59002487-7dc7d280-87c7-11e9-9e4e-7f0f4293c489.png">

## Unselected
<img width="795" alt="Messages darkmode bug 2" src="https://user-images.githubusercontent.com/16657986/59002492-828c8680-87c7-11e9-8954-7792185a8f73.png">

Mojave 10.14.4
Mid 2015 MacBook
darkmode 1.8.2

**Comment by katernet** [comment]
My first thought is a macOS bug. Try uninstall my darkmode and leave macOS dark mode on for a while and see if Messages bugs like that in the morning. Edit: You seem to have dark mode off. Try toggling it on/off or off/on every so often manually ¯\\_(ツ)_/¯

If it still does this then it's a macOS bug, if it doesn't then I am not really sure how to fix this, as all my script does is automate the turning on of dark mode.

**Comment by pelillian** [comment]
OK, I did this and I can't seem to reproduce the error without using your script.

**Comment by katernet** [comment]
Unable to fix. Unless anyone else can find a bug.

When this script changes to dark mode, it uses Apple Script which instantly changes the window color, compared to the built in which transitions smoothly. Unfortunately there is currently no other way to change to dark mode programatically using shell script. Thanks for bringing this to our attention.

Catalina will introduce an 'Auto' option for dark mode, which shouldn't have this issue being a built in. I'll be updating the README when I finish the new version that I am working on.
