### ISSUE TITLE
The script should run only once on load (wake)

### ISSUE THREAD

**Issue by driver733** [katernet/darkmode#5]
The script should run only once on load (wake)
As per https://github.com/katernet/darkmode/issues/4#issuecomment-416598914

**Comment by katernet** [comment]
Can I confirm you've cloned the latest commit https://github.com/katernet/darkmode/commit/8a0db1d72cd941fb566df87eec7d6d89fe4f2c00 or used the latest 1.7 release from 13 hours ago?

**Comment by driver733** [comment]
@katernet Yes, I did (I used 1.7). BTW, I have not checked if the stated issue actually exists or not. I just wanted to record the issue that you mentioned in the [comment](url
https://github.com/katernet/darkmode/issues/4#issuecomment-416598914).

p.s. Thank you for script! :) I have sent a suggestion to Apple to include auto dark mode in Mojave with reference to you github repo.

**Comment by katernet** [comment]
Oh ok. I still made a new commit and release to fix that after closing #4 

Thanks for the reference!
