### ISSUE TITLE
Suggestion: Run on manual "night shift"

### ISSUE THREAD

**Issue by jessevdp** [katernet/darkmode#8]
Hi, I have no clue if this is at all possible... currently this solution turns on dark mode based on the times setup in night shift right? What if we could toggle dark mode based on weather or not "night shift" was on? That would me to turn into complete low-light mode if I was working in a dark room... and allow me to just turn back to light mode if I was in bright conditions again.

Let me know if this is doable! 😃Happy to contribute, although I am no good writing bash scripts.

**Comment by katernet** [comment]
Hi @jessevdp thanks for the request. darkmode is intrinsically centred around running on a launchd schedule at sunrise/sunset times, I am fairly sure you can't use launchd to watch for the Night Shift status. You could maybe use bash to check, but then how could it automate? I am not sure how to implement this. Maybe someone has a bright idea to implement this; I'll leave this issue open for a while.

Here is a utility that could allow you to achieve what you are after https://github.com/ApolloZhu/Dynamic-Dark-Mode it has an option to set Dark Mode based on lighting conditions. It is coded in Swift, which I am not well versed in.

**Comment by jessevdp** [comment]
Hmm I see, it's not like you can tap into some sort of system event the
same way you can tap into time events I guess...

Quick Google search resulted in nothing... But perhaps someone has more
expertise ;)
