### ISSUE TITLE
Not shifting on sunrise

### ISSUE THREAD

**Issue by axelra82** [katernet/darkmode#9]
When running darkmode.sh the first time (at night time) it shifted from light to dark (and installed all dependencies). But this morning it did not shift back to light.

When running darkmode.sh (from library/application support) it says
/Users/[MY_USERNAME]/Library/Application\ Support/darmode/darkmode.sh ; exit;
-bash: /Users/[MY_USERNAME]/.profile: No such file or directory
[MY_USERNAME]:~[MY_USERNAME]$ /Users/[MY_USERNAME]/Library/Application\ Support/darmode/darkmode.sh ; exit;

From the log file (io.github.katernet.darkmode.log)
10/01/18 22:41:03 Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
10/01/18 22:41:03 date: illegal time format
10/01/18 22:41:03 usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
10/01/18 22:41:03             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
10/01/18 22:41:03 Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
10/01/18 22:41:03 date: illegal time format
10/01/18 22:41:03 usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
10/01/18 22:41:03             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
01/10/18 22:41:03 darkmode: Solar query stored - Sunrise:  Sunset:

**Comment by katernet** [comment]
Are you sure you are running the script correctly? From the output it mentions 'exit' and the file .profile which is mentioned nowhere in the script. Please make sure you running the script as per the below methods.

```
$ cd [folder where script is located]
$ ./darkmode.sh
```

Or just drag darkmode.sh into Terminal (with an empty shell of course)

Also you shouldn't have to run the script manually again when it is working correctly (I understand yours isn't).

It seems from the log that no sunrise/sunset times are being picked up, as indicated by the empty quotes `''`. Which model and year of Mac do you have? If it does not support Night Shift then you will need to use v1.7.2 - See the system requirements at https://support.apple.com/en-au/HT207513

**Comment by katernet** [comment]
Closing due to no response. Issue is also being discussed in #10

**Comment by axelra82** [comment]
Hi,
Thank for replying... actually the problem is that it's not switching back after sunrise (to light mode). But the dark mode activates just fine on sunset.
